# Generated by Django 4.2.9 on 2024-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_successfully',
            field=models.BooleanField(default=False),
        ),
    ]
