# Generated by Django 4.2.9 on 2024-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_uploadedfile_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
