# Generated by Django 5.0.2 on 2024-03-16 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0003_alter_uploadedfile_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_content',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
