# Generated by Django 5.0.2 on 2024-03-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0004_uploadedfile_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_content',
        ),
    ]
