# Generated by Django 5.0.2 on 2024-03-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0006_uploadedfile_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='cas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
