# Generated by Django 5.0.2 on 2024-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0008_alter_uploadedfile_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
