# Generated by Django 5.0.2 on 2024-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0009_alter_uploadedfile_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
