# Generated by Django 5.0.2 on 2024-03-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0010_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
