# Generated by Django 5.0.2 on 2024-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0012_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(max_length=255),
        ),
    ]
