# Generated by Django 5.0.2 on 2024-03-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0013_alter_uploadedfile_original_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='cas',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='method',
        ),
    ]
