# Generated by Django 5.0.2 on 2024-04-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0014_remove_uploadedfile_cas_remove_uploadedfile_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(max_length=999),
        ),
    ]
